# Generated by Django 5.0.6 on 2024-05-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parlor_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
