# Generated by Django 5.0.6 on 2024-05-16 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_parlor_app', '0003_customerorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='vehicles',
            field=models.ManyToManyField(to='bike_parlor_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bike_parlor_app.customer'),
        ),
    ]
